language: java

jdk:
  - oraclejdk8

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  PYTHON: "C:\\Python35"
  dotnetcore_version: 2.1.302
  nodejs_version: "8"  

branches:
  only:
    - master

build_script:
  - ps: >
      .\script\script.ps1  


